name: minty
favicon: null
layout_spectrum: 0.3603073819540441
typography_spectrum: 0.1272554302122444
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.21257390291430056
  lightness: 0.33056743047200143
  saturation: 0.4992160447873175
  rhythmicContrast: 0.09332347917370498
purpose: []
